# ROOST_METHOD_HASH=initialize_faiss_a20dc91182
# ROOST_METHOD_SIG_HASH=initialize_faiss_185df1f699

"""Tests for `inference.initialize_faiss`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: inference.py:8-26
# Scenarios:
#   - [happy_path] successful_initialization: Verify that the function correctly initializes embeddings and loads the FAISS index when everything is present and valid.
#   - [error_path] load_local_failure: Verify that the function handles failures during FAISS index loading by returning None.
#   - [error_path] embeddings_initialization_failure: Verify that failures during embeddings initialization are not caught and bubble up.
#   - [edge_case] corrupt_index_file: Verify that the function handles corrupt index files gracefully by returning None.

import pytest
from unittest.mock import patch, MagicMock
from inference import initialize_faiss

@pytest.mark.generated
@pytest.mark.happy_path
def test_successful_initialization():
    """Verify that the function correctly initializes embeddings and loads the FAISS index when everything is present and valid."""
    # NB: Patching at the SUT's namespace as per Rule 2.
    with patch("inference.HuggingFaceEmbeddings") as mock_embeddings_cls, \
         patch("inference.FAISS.load_local") as mock_load_local:
        
        mock_db = MagicMock()
        mock_load_local.return_value = mock_db
        mock_embeddings_instance = MagicMock()
        mock_embeddings_cls.return_value = mock_embeddings_instance
        
        result = initialize_faiss()
        
        assert result == mock_db
        mock_embeddings_cls.assert_called_once_with(
            model_name="sentence-transformers/all-MiniLM-l6-v2",
            model_kwargs={'device': 'cpu'},
            encode_kwargs={'normalize_embeddings': False}
        )
        mock_load_local.assert_called_once_with(
            folder_path="./faiss_db",
            index_name="Index",
            embeddings=mock_embeddings_instance,
            allow_dangerous_deserialization=True
        )

@pytest.mark.generated
@pytest.mark.error_path
def test_load_local_failure():
    """Verify that the function handles failures during FAISS index loading by returning None."""
    with patch("inference.HuggingFaceEmbeddings"), \
         patch("inference.FAISS.load_local") as mock_load_local:
        
        mock_load_local.side_effect = Exception("Load failed")
        
        result = initialize_faiss()
        
        assert result is None

@pytest.mark.generated
@pytest.mark.error_path
def test_embeddings_initialization_failure():
    """Verify that failures during embeddings initialization are not caught and bubble up."""
    with patch("inference.HuggingFaceEmbeddings") as mock_embeddings_cls:
        mock_embeddings_cls.side_effect = Exception("Initialization failed")
        
        with pytest.raises(Exception, match="Initialization failed"):
            initialize_faiss()

@pytest.mark.generated
@pytest.mark.edge_case
def test_corrupt_index_file():
    """Verify that the function handles corrupt index files gracefully by returning None."""
    with patch("inference.HuggingFaceEmbeddings"), \
         patch("inference.FAISS.load_local") as mock_load_local:
        
        mock_load_local.side_effect = RuntimeError("Corrupt index file")
        
        result = initialize_faiss()
        
        assert result is None
