# ROOST_METHOD_HASH=search_with_score_1fad99c4ed
# ROOST_METHOD_SIG_HASH=search_with_score_72e435d7ec

"""Tests for `inference.search_with_score`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: inference.py:29-47
# Scenarios:
#   - [happy_path] happy_path_success: Verify the happy path where a query returns a result from the DB and a response from the LLM.
#   - [edge_case] empty_search_results: Verify behavior when the vector database returns no matching documents.
#   - [happy_path] multiple_search_results: Verify that multiple search results are correctly formatted and passed to the LLM chain.
#   - [error_path] retrieval_chain_failure: Verify that exceptions from the LangChain retrieval chain are correctly propagated.
#   - [error_path] db_is_none: Verify behavior when the database object is None.

import pytest
from unittest.mock import MagicMock, patch
from inference import search_with_score

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_success():
    """Verify the happy path where a query returns a result from the DB and a response from the LLM."""
    mock_db = MagicMock()
    # Mocking Document as a simple object whose str() returns its content
    mock_doc = MagicMock()
    mock_doc.__str__.return_value = "MIT is a college"
    mock_db.similarity_search_with_score.return_value = [(mock_doc, 0.9)]
    
    mock_retriever = MagicMock()
    mock_db.as_retriever.return_value = mock_retriever

    with patch("inference.Ollama") as mock_ollama, \
         patch("inference.ChatPromptTemplate.from_template") as mock_from_template, \
         patch("inference.create_stuff_documents_chain") as mock_create_stuff, \
         patch("inference.create_retrieval_chain") as mock_create_retrieval:
        
        mock_chain = MagicMock()
        expected_output = {'answer': 'MIT is Manipal Institute of Technology', 'context': [], 'input': 'What is MIT?MIT is a college: 0.9'}
        mock_chain.invoke.return_value = expected_output
        mock_create_retrieval.return_value = mock_chain
        
        result = search_with_score(mock_db, "What is MIT?")
        
        assert result == expected_output
        mock_db.similarity_search_with_score.assert_called_once_with("What is MIT?")
        mock_chain.invoke.assert_called_once_with({"input": "What is MIT?MIT is a college: 0.9"})

@pytest.mark.generated
@pytest.mark.edge_case
def test_empty_search_results():
    """Verify behavior when the vector database returns no matching documents."""
    mock_db = MagicMock()
    mock_db.similarity_search_with_score.return_value = []
    
    with patch("inference.Ollama"), \
         patch("inference.ChatPromptTemplate.from_template"), \
         patch("inference.create_stuff_documents_chain"), \
         patch("inference.create_retrieval_chain") as mock_create_retrieval:
        
        mock_chain = MagicMock()
        expected_output = {'answer': 'I don\'t know', 'context': [], 'input': 'Unknown'}
        mock_chain.invoke.return_value = expected_output
        mock_create_retrieval.return_value = mock_chain
        
        result = search_with_score(mock_db, "Unknown")
        
        assert result == expected_output
        mock_db.similarity_search_with_score.assert_called_once_with("Unknown")
        mock_chain.invoke.assert_called_once_with({"input": "Unknown"})

@pytest.mark.generated
@pytest.mark.happy_path
def test_multiple_search_results():
    """Verify that multiple search results are correctly formatted and passed to the LLM chain."""
    mock_db = MagicMock()
    doc1 = MagicMock()
    doc1.__str__.return_value = "Doc1"
    doc2 = MagicMock()
    doc2.__str__.return_value = "Doc2"
    mock_db.similarity_search_with_score.return_value = [(doc1, 0.1), (doc2, 0.2)]
    
    with patch("inference.Ollama"), \
         patch("inference.ChatPromptTemplate.from_template"), \
         patch("inference.create_stuff_documents_chain"), \
         patch("inference.create_retrieval_chain") as mock_create_retrieval:
        
        mock_chain = MagicMock()
        mock_create_retrieval.return_value = mock_chain
        
        search_with_score(mock_db, "query")
        
        # searchresult = 'Doc1: 0.1 Doc2: 0.2'
        # llminput = 'queryDoc1: 0.1 Doc2: 0.2'
        mock_chain.invoke.assert_called_once_with({"input": "queryDoc1: 0.1 Doc2: 0.2"})

@pytest.mark.generated
@pytest.mark.error_path
def test_retrieval_chain_failure():
    """Verify that exceptions from the LangChain retrieval chain are correctly propagated."""
    mock_db = MagicMock()
    mock_db.similarity_search_with_score.return_value = []
    
    with patch("inference.Ollama"), \
         patch("inference.ChatPromptTemplate.from_template"), \
         patch("inference.create_stuff_documents_chain"), \
         patch("inference.create_retrieval_chain") as mock_create_retrieval:
        
        mock_chain = MagicMock()
        mock_chain.invoke.side_effect = ValueError('LLM connection failed')
        mock_create_retrieval.return_value = mock_chain
        
        with pytest.raises(ValueError, match='LLM connection failed'):
            search_with_score(mock_db, "query")

@pytest.mark.generated
@pytest.mark.error_path
def test_db_is_none():
    """Verify behavior when the database object is None."""
    with pytest.raises(AttributeError):
        search_with_score(None, "query")
